//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCliente
    {
        public string id { get; set; }
        public int tipoCliente { get; set; }
        public System.DateTime fecha_socio { get; set; }
        public bool estado { get; set; }
    
        public virtual tbTipoCliente tbTipoCliente { get; set; }
        public virtual tbPersona tbPersona { get; set; }
    }
}
